/*!
 * Craft by Pixel & Tonic
 *
 * @package   Craft
 * @author    Pixel & Tonic, Inc.
 * @copyright Copyright (c) 2013, Pixel & Tonic, Inc.
 * @license   http://buildwithcraft.com/license1.0.html Craft License
 * @link      http://buildwithcraft.com
 */
(function(d){var a=Garnish.Base.extend({messages:null,init:function(){this.messages=[];var h=d("#messages"),f=h.find(".message");for(var e=0;e<f.length;e++){var g=new b(f[e]);this.messages.push(g)}}});var b=Garnish.Base.extend({$container:null,key:null,$subject:null,$body:null,modal:null,init:function(e){this.$container=d(e);this.key=this.$container.attr("data-key");this.$subject=this.$container.find(".subject:first");this.$body=this.$container.find(".body:first");this.addListener(this.$container,"click","edit")},edit:function(){if(!this.modal){this.modal=new c(this)}else{this.modal.show()}},updateHtmlFromModal:function(){var f=this.modal.$subjectInput.val(),e=this.modal.$bodyInput.val().replace(/\n/g,"<br>");this.$subject.html(f);this.$body.html(e)}});var c=Garnish.Modal.extend({message:null,$localeSelect:null,$subjectInput:null,$bodyInput:null,$saveBtn:null,$cancelBtn:null,$spinner:null,loading:false,init:function(e){this.message=e;this.base();this.loadContainer()},loadContainer:function(e){var f={key:this.message.key,locale:e};d.post(Craft.getUrl("settings/email/_message_modal"),f,d.proxy(function(g,j,h){if(!this.$container){var i=d('<form class="modal message-settings" accept-charset="UTF-8">'+g+"</form>").appendTo(Garnish.$bod);this.setContainer(i);this.show()}else{this.$container.html(g)}this.$localeSelect=this.$container.find(".locale:first > select");this.$subjectInput=this.$container.find(".message-subject:first");this.$bodyInput=this.$container.find(".message-body:first");this.$saveBtn=this.$container.find(".submit:first");this.$cancelBtn=this.$container.find(".cancel:first");this.$spinner=this.$container.find(".spinner:first");this.addListener(this.$localeSelect,"change","switchLocale");this.addListener(this.$container,"submit","saveMessage");this.addListener(this.$cancelBtn,"click","cancel");setTimeout(d.proxy(function(){this.$subjectInput.focus()},this),100)},this))},switchLocale:function(){var e=this.$localeSelect.val();this.loadContainer(e)},saveMessage:function(e){e.preventDefault();if(this.loading){return}var f={key:this.message.key,locale:(this.$localeSelect.length?this.$localeSelect.val():Craft.language),subject:this.$subjectInput.val(),body:this.$bodyInput.val()};this.$subjectInput.removeClass("error");this.$bodyInput.removeClass("error");if(!f.subject||!f.body){if(!f.subject){this.$subjectInput.addClass("error")}if(!f.body){this.$bodyInput.addClass("error")}Garnish.shake(this.$container);return}this.loading=true;this.$saveBtn.addClass("active");this.$spinner.show();Craft.postActionRequest("emailMessages/saveMessage",f,d.proxy(function(g,i,h){if(g.success){if(f.locale==Craft.language){this.message.updateHtmlFromModal()}this.hide();Craft.cp.displayNotice(Craft.t("Message saved."))}else{Craft.cp.displayError(Craft.t("Couldn’t save message."))}this.$saveBtn.removeClass("active");this.$spinner.hide();this.loading=false},this))},cancel:function(){this.hide();if(this.message){this.message.modal=null}}});new a()})(jQuery);