/*!
 * Craft by Pixel & Tonic
 *
 * @package   Craft
 * @author    Pixel & Tonic, Inc.
 * @copyright Copyright (c) 2013, Pixel & Tonic, Inc.
 * @license   http://buildwithcraft.com/license1.0.html Craft License
 * @link      http://buildwithcraft.com
 */
(function(a){var b=Garnish.Base.extend({$form:null,$protocolField:null,$protocolSelect:null,$hiddenFields:null,$testBtn:null,$testSpinner:null,$protocolSettingsPane:null,$protocolSettingsPaneHead:null,$protocolSettingsPaneBody:null,protocol:null,init:function(){this.$form=a("#settings-form");this.$protocolField=a("#protocol-field");this.$protocolSelect=a("#protocol");this.$hiddenFields=a("#hidden-fields");this.$testBtn=a("#test");this.$testSpinner=a("#test-spinner");this._onEmailTypeChange();this.addListener(this.$protocolSelect,"change","_onEmailTypeChange");this.addListener(this.$testBtn,"activate","sendTestEmail")},getField:function(c){return a("#"+b.protocolFields[this.protocol][c]+"-field")},_onEmailTypeChange:function(){if(this.protocol&&this.protocol in b.protocolFields){for(var e=0;e<b.protocolFields[this.protocol].length;e++){this.getField(e).appendTo(this.$hiddenFields)}}this.protocol=this.$protocolSelect.val();if(this.protocol in b.protocolFields){var c=this.$protocolField;for(var d=0;d<b.protocolFields[this.protocol].length;d++){var f=this.getField(d);f.insertAfter(c);c=f}}},sendTestEmail:function(){if(this.$testBtn.hasClass("sel")){return}this.$testBtn.addClass("sel");this.$testSpinner.removeClass("hidden");var c=Garnish.getPostData(this.$form);delete c.action;Craft.postActionRequest("systemSettings/testEmailSettings",c,a.proxy(function(d){this.$testBtn.removeClass("sel");this.$testSpinner.addClass("hidden");if(d.success){alert(Craft.t("Email sent successfully! Check your inbox."))}else{var e=d.error||Craft.t("An unknown error occurred.");alert(e)}},this))}},{protocolFields:{smtp:["host","port","smtpKeepAlive","smtpAuth","smtpAuthCredentials","smtpSecureTransportType","timeout"],pop:["username","password","host","port","timeout"],gmail:["username","password"]}});Craft.emailSettingsForm=new b()})(jQuery);