/*!
 * Craft by Pixel & Tonic
 *
 * @package   Craft
 * @author    Pixel & Tonic, Inc.
 * @copyright Copyright (c) 2013, Pixel & Tonic, Inc.
 * @license   http://buildwithcraft.com/license1.0.html Craft License
 * @link      http://buildwithcraft.com
 */
(function(a){Craft.Installer=Garnish.Base.extend({$screens:null,$currentScreen:null,$accountSubmitBtn:null,$siteSubmitBtn:null,loading:false,init:function(){this.$screens=Garnish.$bod.children(".modal");this.addListener(a("#beginbtn"),"activate","showAccountScreen")},showAccountScreen:function(b){this.showScreen(1,a.proxy(function(){a("#beginbtn").remove();this.$accountSubmitBtn=a("#accountsubmit");this.addListener(this.$accountSubmitBtn,"activate","validateAccount");this.addListener(a("#accountform"),"submit","validateAccount")},this))},validateAccount:function(c){c.preventDefault();var b=["username","email","password"];this.validate("account",b,a.proxy(this,"showSiteScreen"))},showSiteScreen:function(){this.showScreen(2,a.proxy(function(){this.$siteSubmitBtn=a("#sitesubmit");this.addListener(this.$siteSubmitBtn,"activate","validateSite");this.addListener(a("#siteform"),"submit","validateSite")},this))},validateSite:function(c){c.preventDefault();var b=["siteName","siteUrl"];this.validate("site",b,a.proxy(this,"showInstallScreen"))},showInstallScreen:function(){this.showScreen(3,a.proxy(function(){var b=["username","email","password","siteName","siteUrl","locale"];var e={};for(var d=0;d<b.length;d++){var c=b[d],f=a("#"+c);e[c]=Garnish.getInputPostVal(f)}Craft.postActionRequest("install/install",e,a.proxy(this,"allDone"))},this))},allDone:function(){this.$currentScreen.find("h1:first").text(Craft.t("All done!"));var b=a('<div class="buttons"><a href="'+Craft.getUrl("dashboard")+'" class="btn big submit">'+Craft.t("Go to Craft")+"</a></div>");a("#spinner").replaceWith(b)},showScreen:function(d,e){var c=Garnish.$win.width(),b=Math.floor(c/2);if(this.$currentScreen){this.$currentScreen.css("left",b).animate({left:-730},"fast")}this.$currentScreen=a(this.$screens[d-1]).css({display:"block",left:c+370}).animate({left:b},"fast",a.proxy(function(){this.$currentScreen.css("left","50%");this.focusFirstInput();e()},this))},validate:function(g,e,k){if(this.loading){return}this.loading=true;a("#"+g+"form").find(".errors").remove();var j=this["$"+g+"SubmitBtn"];j.addClass("sel loading");var b="install/validate"+Craft.uppercaseFirst(g);var c={};for(var d=0;d<e.length;d++){var h=e[d],f=a("#"+h);c[h]=Garnish.getInputPostVal(f)}Craft.postActionRequest(b,c,a.proxy(function(m){if(m.validates){k()}else{for(var l in m.errors){var s=m.errors[l],r=a("#"+l),q=r.closest(".field"),o=a('<ul class="errors"/>').appendTo(q);for(var p=0;p<s.length;p++){var n=s[p];a("<li>"+n+"</li>").appendTo(o)}if(!r.is(":focus")){r.addClass("error");(a.proxy(function(i){this.addListener(i,"focus",function(){i.removeClass("error");this.removeListener(i,"focus")})},this))(r)}}Garnish.shake(this.$currentScreen)}this.loading=false;j.removeClass("sel loading")},this))},focusFirstInput:function(){setTimeout(a.proxy(function(){this.$currentScreen.find("input:first").focus()},this),300)}});Garnish.$win.on("load",function(){Craft.installer=new Craft.Installer()})})(jQuery);